
volumes:
  agentdata:

networks:
  frontend:
  backend:

services:
  mysql:
    image: 'mysql:9.0.1'
    container_name: mysql_database
    volumes:
      - agentdata:/var/lib/mysql
    networks:
      - backend
    environment:
      - MYSQL_ROOT_PASSWORD=mysecret
      - bind-address=0.0.0.0

  dbinit:
    build:
      context: .
      dockerfile: ./MySQLRESTDataProvider/Dockerfile
    networks:
      - backend
    environment:
      - INITDB=true
      - DBHOST=mysql
    depends_on:
      - mysql

  mvcdata:
    container_name: rest_mysql_dataprovider
    build:
      context: .
      dockerfile: ./MySQLRESTDataProvider/Dockerfile
    networks:
      - backend
      - frontend
#    volumes:
#      - ~/.aspnet/https:/https:ro
#      - ./Certs:/https:ro
#      - ~/.aspnet/https:/root/.aspnet/https:ro
#      - ~/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro
    ports:
      - 5148:5148
#     - 8001:443
    environment:
      - DBHOST=mysql
      - ASPNETCORE_URLS=http://+:5148
#      - ASPNETCORE_HTTPS_PORT=8001
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_Kestrel__Certificates__Default__Password=MySecurePwd1@
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/exampleapp.pfx 
    depends_on:
      - mysql
  
  mvc:
    container_name: agent_mvc
    build:
      context: .
      dockerfile: ./MVC/Dockerfile
    networks:
      - frontend
#    volumes:
#      - ~/.aspnet/https:/https:ro
#      - ./Certs:/https:ro
#      - ~/.aspnet/https:/root/.aspnet/https:ro
#      - ~/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro
    ports:
      - 5148:3000
#      - 8001:443
    environment:
      - DBHOST=mysql
      - ASPNETCORE_URLS=http://+:80
#      - ASPNETCORE_HTTPS_PORT=8001
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_Kestrel__Certificates__Default__Password=MySecurePwd1@
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/exampleapp.pfx 
    depends_on:
      - mvcdata

  loadbalancer:
    container_name: agent_loadbalancer
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 3000:8080
#      - 3001:443
    depends_on:
      - mvc
    networks:
      - frontend
    links:
      - mvc
